### ISSUE TITLE
Release Process Fails

### ISSUE THREAD

**Issue by gabpil45** [jenkinsci/pipeline-github-plugin#100]
### Reproduction steps

- Automatic release triggers

### Results

Expected result:

- GH Actions to finish without errors

Actual result:

- GH Actions fails on multiple spotbug checks
   https://github.com/jenkinsci/pipeline-github-plugin/runs/2970551618?check_suite_focus=true#step:4:176

**Comment by aaronwalker** [comment]
fixed release process https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/pipeline-github/2.8-138.d766e30bb08b/
