### ISSUE TITLE
issueCommentTrigger not working when collaborator is part of GitHub Teams

### ISSUE THREAD

**Issue by cjoyv** [jenkinsci/pipeline-github-plugin#107]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

issueCommentTrigger not working when collaborator is part of GitHub Teams added to the repo

### Expected Results

It should consider the members of a team when looking at collaborators

### Actual Results

GitHub Team members are not considered as collaborators. Only if a member is directly added to repository as collaborator, issueComments are trigggering the build

**Comment by emas80** [comment]
I had the same problem after switching from using a Github token to using a Github App.

I have solved it by adding one more permission to my app - the Administration Read Only

![image](https://user-images.githubusercontent.com/2953749/156176271-06b8380b-ba37-4c10-90f9-75d2badd254f.png)

The plugin can now read correctly the permissions the user has on the repo.

**Comment by cjoyv** [comment]
I think my issue is with plugin doesn't supporting Team membership. When a GitHub team is given access to the repo, all of its members gets that access. If collaborator is part of a team with Admin access, the plugin gives an error saying **"cjoyv is not a collaborator, and is therefore not authorized to trigger a build"**

**Comment by xocasdashdash** [comment]
Hi there! 
We're hitting the same issue someone on this ticket and from here it seems to happen too https://github.com/jenkinsci/pipeline-github-plugin/issues/104#issuecomment-920833823 

Seems like the way the underlying library fetches collaborators is not team membership friendly. Could we add a flag to disable it as suggested? Another approach could be to implement the flow "correctly", check the user team, get the team permissions and see if any of the teams can write on the repository

**Comment by nick-tripp** [comment]
I'm also experiencing this issue in my org - definitely seems like good bug to fix

**Comment by xocasdashdash** [comment]
My PR #111 fixes it, but not sure how much time it's going to take to get this merged 😕

**Comment by snorlaX-sleeps** [comment]
I wonder if there is anyone we could tag for your PR @xocasdashdash - the fix listed above (add more app permissions) doesn't work when using teams, the user has to be directly added to the repo which wouldn't work in my use-case

**Comment by xocasdashdash** [comment]
@snorlaX-sleeps in the PR #111 Aaron posted a link to test it out, if you can validate the plugin we can probably get this merged soon!

**Comment by xocasdashdash** [comment]
This issue can be closed as #111  has been merged. Not sure when it's going to be released though @aaronwalker
