### ISSUE TITLE
Expose Pull Request Review Approvals

### ISSUE THREAD

**Issue by TreyLawrence** [jenkinsci/pipeline-github-plugin#16]
I'd like to auto-merge pull requests when our tests pass and reviewers have approved, but the only thing exposed on the pull requests are individual review comments instead of full reviews from this endpoint:
https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

So as of now, there's no way for me to block a pull request merge if a reviewer hasn't approved it.

**Comment by juhtie01** [comment]
I am just working with the same topic. I tried the documented `if (pullRequest.mergeable)` construct, but that does not seem to take missing approvals into account.

**Comment by deiwin** [comment]
I have the same need and just opened #18 to address this. Feedback is welcome.
