### ISSUE TITLE
How to check if it is pullrequest or just branch?

### ISSUE THREAD

**Issue by Wing924** [jenkinsci/pipeline-github-plugin#2]
I check it by:
```groovy
def isPullRequest() {
    try {
        return pullRequest != null
    } catch(MissingPropertyException e) {
        return false
    }
}
```
Is there any better way to do this?

**Comment by aaronjwhiteside** [comment]
```groovy
if (env.CHANGE_ID) {
   // pull request
}
```

This environment variable is set by the github branch source plugin.

This stackoverlow article explains how to view all the environment variables: https://stackoverflow.com/questions/41604854/environment-variable-in-jenkins-pipeline

**Comment by itninja-hue** [comment]
@namjitharavind 
```groovy
if (env.BRANCH_NAME != 'master' && env.CHANGE_ID == null){
}
```

**Comment by gideonaina** [comment]
> ```groovy
> if (env.BRANCH_NAME != 'master' && env.CHANGE_ID == null){
> }
> ```

For a multipipeline job it will be 
```
if (env.CHANGE_BRANCH != 'master' && env.CHANGE_ID == null){
}
```
env.BRANCH_NAME has a different value in a multipipeline job (at least for the version of plugin)

**Comment by amtux** [comment]
i came here looking for a solution but got it working a little differently. using declarative syntax - you can also do:

```groovy
    stage('run-on-pr') {
      when {
        expression { env.CHANGE_ID ==~ /.*/ }
      }
      steps {
        echo "this is a pull request"
      }
    }
```

same idea as before - checks to see `CHANGE_ID` env var is populated.
