### ISSUE TITLE
NotSerializableException: ... CommitStatusGroovyObject

### ISSUE THREAD

**Issue by manthanhd** [jenkinsci/pipeline-github-plugin#22]
Hey,

I'm running this in a pipeline and while it works for most part, I'm now seeing this error. This happens because Jenkins on occasions takes snapshots of all variables so that it can recover the pipeline in case there was a crash. At the moment I am seeing the following exception:

```
Caused: java.io.NotSerializableException: org.jenkinsci.plugins.pipeline.github.CommitStatusGroovyObject
```

Can you please update the class to implement Serializable or do something so that it is serializable?

Thanks,

**Comment by manthanhd** [comment]
I have currently worked around this issue by doing:
```
@NonCPS
def createStatus(params) {
  pullRequest.createStatus(params)
}
```

but I would appreciate this being fixed.

**Comment by aaronjwhiteside** [comment]
All `*GroovyObject`'s now implement `Serializable` in https://github.com/jenkinsci/pipeline-github-plugin/commit/c5b44b177e67d19cfd8544d87248bb53215cb38d
