### ISSUE TITLE
Deleting a comment with the trigger phrase triggers the build, as if the comment was added

### ISSUE THREAD

**Issue by eplodn** [jenkinsci/pipeline-github-plugin#29]
Probably need to look for `{"action": "created"}` in the Github webhook POST contents.

**Comment by maurofaccenda** [comment]
I am facing the same problem. Did anyone already took a look here?

**Comment by aaronjwhiteside** [comment]
Thanks @eplodn for reporting this issue, this is now fixed in the next release.

**Comment by Elderry** [comment]
Looking forward to have this issue fixed.
