### ISSUE TITLE
pullRequest.createStatus Reports status to the pull request fork, not the fork being submitted to

### ISSUE THREAD

**Issue by aaronjwhiteside** [jenkinsci/pipeline-github-plugin#30]
Copied from: https://issues.jenkins-ci.org/browse/JENKINS-52553

When a pull request from a different fork is created, all statuses get posted to the fork of the submitter, and not the target. This causes issues with the pull request, because on the Github PR page, there is seemingly no status reported by Jenkins.

My fork gshieh/my_code is trying to submit a change into TheCompany/my_code

I have an idea why this is occurring. The plugin is POST-ing to
/repos/gshieh/my_code/statuses/3776fe0c93c2588af558a1adb88918fd439524ee
not to
/repos/TheCompany/my_code/statuses/3776fe0c93c2588af558a1adb88918fd439524ee

**Comment by aaronjwhiteside** [comment]
So I remember this issue from early on in the plugins development, it's an issue with using forks vs creating a feature/bugfix/whatever branch in the target repository.

https://developer.github.com/v3/repos/statuses/

The GitHub statuses API is for adding statues to commits, and your commit is on your fork, not the target repository of the Pull Request. It'll be on the target repository of the Pull Request once you merge through.. 

In an enterprise environment I would suggest you create a new feature branch instead of using a fork and do your work there. Security can be managed via protected branches etc.. 

Forks are great for open source projects where you don't want to give everyone write access to your repo (even with protected branches, because they can create an unlimited number of branches..)
https://help.github.com/articles/about-protected-branches/

**Comment by chancez** [comment]
Yeah this is really unfortunate, I was hoping to use this instead of other steps for setting the PR status.

**Comment by nrayapati** [comment]
Made a pull request to fix this behavior https://github.com/jenkinsci/pipeline-github-plugin/pull/42

**Comment by nrayapati** [comment]
@aaronjwhiteside As soon as the PR is opened the commit becomes part of the repo to which the pull request is made, it doesn't need to be merged to change the status on that commit, now this is commit is part of the PR instead of any other branch.
