### ISSUE TITLE
addLabel API issues?

### ISSUE THREAD

**Issue by dwbruhn** [jenkinsci/pipeline-github-plugin#31]
Calling the [`addLabel` API](https://github.com/jenkinsci/pipeline-github-plugin#adding-a-label) like `pullRequest.addLabel("Common Files")` was failing with this exception:

> hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.addLabel() is applicable for argument types: (java.lang.String) values: [Common Files]

Switching it to `addLabels` (plural) like `pullRequest.addLabels(["Common Files"] as String[])` succeeded.

Not sure what was wrong with the way I was calling `addLabel`, but the README seems to be wrong there.

**Comment by aaronjwhiteside** [comment]
@dwbruhn Thanks for reporting this!

**Comment by aaronjwhiteside** [comment]
Fixed in https://github.com/jenkinsci/pipeline-github-plugin/commit/f1580b2454d40eed6712ac466153211e579d7f5e
