### ISSUE TITLE
createReviewRequests failing

### ISSUE THREAD

**Issue by johanek** [jenkinsci/pipeline-github-plugin#34]
Hi there,

When I try to add review requests to a PR with code like:

```pullRequest.createReviewRequests('johanek')```

It fails so:

```hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.createReviewRequests() is applicable for argument types: (java.lang.String) values: [johanek]```

Thanks!

**Comment by aaronjwhiteside** [comment]
This method takes a List of Strings, but I think you've found a good issue, we should overload this method to take a single String param.

In the meantime, can you try `pullRequest.createReviewRequests(['johanek'])`?

**Comment by johanek** [comment]
Hello,

It works fine when given a list - which is what I really wanted to do, to add multiple reviewers. I've created a PR for the README so that the example shows passing a list.

Thanks for the really useful project!

**Comment by aaronjwhiteside** [comment]
Fixed in commit https://github.com/jenkinsci/pipeline-github-plugin/commit/8b358472be61aa92d0d46991986bbdbff464a79a
