### ISSUE TITLE
Cannot edit pull request

### ISSUE THREAD

**Issue by danpalmer** [jenkinsci/pipeline-github-plugin#41]
When I try to set the body of a pull request I get the following:

```
java.net.ProtocolException: Invalid HTTP method: PATCH
```

It looks like internally a pull request edit is created, and then `patch`ed against the API. It seems that something in Java doesn't like this, or perhaps upstream at GitHub.

**Comment by danpalmer** [comment]
Ping on this, would be good to figure out whether this is affecting more users.

**Comment by danpalmer** [comment]
Ping. We'd really like to be able to add/update GitHub comments through Jenkins Pipeline, but can't currently do this.

**Comment by danpalmer** [comment]
@aaronjwhiteside here's the relevant part from our Jenkinsfile that was not working:

```groovy
#!/usr/bin/env groovy

API_DIFF_TITLE = "<!-- Do not edit below this line, changes will be discarded. -->\n\n### API Diff"

pipeline {
  stages {
    stage("Tests") {
      parallel {
        stage("Validate API") {
          agent {
            dockerfile {
              label 'docker'
              reuseNode true
            }
          }
          steps {
            script {
              diffOutput = sh(returnStdout: true, script: "scripts/ci-diff-api.js").trim()
              prBodyParts = pullRequest.body.split(API_DIFF_TITLE)
              pullRequest.body = prBodyParts[0] + API_DIFF_TITLE + diffOutput
              if (diffOutput) {
                print(diffOutput)
                error "Backwards incompatible changes detected in API."
              }
            }
          }
        }
      }
    }
  }
}
````

As far as I can tell, this was failing to communicate with the GitHub API because the code issues a PATCH request which I seem to remember had been deprecated or something like that. Jenkins just shows a big Java stacktrace.

**Comment by aaronjwhiteside** [comment]
@danpalmer could you please paste the entire stacktrace here?

**Comment by aaronjwhiteside** [comment]
thanks @danpalmer for reporting this, this is now fixed expect a new release soon!

**Comment by danpalmer** [comment]
Amazing, thank you!
