### ISSUE TITLE
line property of ReviewComment is always null

### ISSUE THREAD

**Issue by phibo23** [jenkinsci/pipeline-github-plugin#44]
I was scripting a Jenkinsfile for adding line comments to pull requests and I wanted to avoid adding the same comment multiple times. I noticed that `getLine()` of `ReviewCommentGroovyObject` always returned `null`

here is a snippet (essentially this example https://github.com/jenkinsci/pipeline-github-plugin#listing-a-pull-requests-review-comments):
```groovy
for (comment in pullRequest.reviewComments) {
    echo "${comment.line}"
}
``` 

and here's the output:
```
[Pipeline] echo
null
[Pipeline] echo
null
[Pipeline] echo
null
[Pipeline] echo
null
[Pipeline] echo
null
```

**Comment by aaronjwhiteside** [comment]
It seems the GitHub API has changed `line` is no longer present, please use `position` instead.

I'll update the README.md.

Thanks for reporting the issue @phibo23!

**Comment by aaronjwhiteside** [comment]
README.md updated in https://github.com/jenkinsci/pipeline-github-plugin/commit/141932703316a25833a4d12cbd1a9c363062e8e7
