### ISSUE TITLE
Timeline for next release

### ISSUE THREAD

**Issue by nrayapati** [jenkinsci/pipeline-github-plugin#50]
@aaronjwhiteside Not sure if you are following comments on this pull request which is being merged already, just wondering about the timelines on the next release of this plugin. 

https://github.com/jenkinsci/pipeline-github-plugin/pull/42

Thank you for all the good work on this plugin.

**Comment by aaronjwhiteside** [comment]
2.2 has been released!

**Comment by nrayapati** [comment]
Thank you very much @aaronjwhiteside
