### ISSUE TITLE
addlabel blocked by Script Security Plugin

### ISSUE THREAD

**Issue by jujardhabarwala** [jenkinsci/pipeline-github-plugin#53]
Below Script in Post Build Section under Multibranch Pipeline (Groovy Script)

script {
                		echo "Hello World"
		
		pullRequest.comment('This PR is highly illogical..')
                if (env.CHANGE_ID) {
                    pullRequest.addLabel('bug')
                }
}

Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject addLabel java.lang.String)

This is due the fact the roovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object is blacklisted in the Script Security plugin

**Comment by aaronjwhiteside** [comment]
The `addLabel()` method was just recently added, the current released version of the plugin does not have the `addLabel()` method.

You'll have to wait until the next release to use the `addLabel()` method :)
