### ISSUE TITLE
only 1.0 is shown in Plugin Manager

### ISSUE THREAD

**Issue by Superluli** [jenkinsci/pipeline-github-plugin#56]
I'm using Jenkins 2.89.2 and I can't see any version available newer than 1.0
![image](https://user-images.githubusercontent.com/2186223/52768071-354e9400-2fe1-11e9-87f0-c76273887cfa.png)

**Comment by aaronjwhiteside** [comment]
version 2.1 is available, but you don't meet the minimum jenkins requirements 

https://plugins.jenkins.io/pipeline-github

please upgrade jenkins to at least 2.128.
