### ISSUE TITLE
Expose "draft" PR property

### ISSUE THREAD

**Issue by thomas-riccardi** [jenkinsci/pipeline-github-plugin#58]
GitHub recently added the concept of Draft Pull Request: https://github.blog/2019-02-14-introducing-draft-pull-requests/

It seems to be a useful property to expose in this plugin, for example to early abort a build.

The value is not yet available by default in the v3 API though:
https://developer.github.com/v3/pulls/#get-a-single-pull-request
> The Draft Pull Request API is currently available for developers to preview. [...] To access the API during the preview period, you must provide a custom media type in the Accept header

**Comment by aaronjwhiteside** [comment]
Good suggestion @thomas-riccardi !

**Comment by thomas-riccardi** [comment]
Since 2019-03-26 it is available by default in the v3 API: https://github.blog/changelog/2019-03-26-create-a-draft-pull-request-from-the-rest-api/

**Comment by aaronjwhiteside** [comment]
Fixed by https://github.com/jenkinsci/pipeline-github-plugin/pull/77
