### ISSUE TITLE
Approve the Pull Request?(Not merging)

### ISSUE THREAD

**Issue by ponsuyambu** [jenkinsci/pipeline-github-plugin#67]
I would like to auto-approve the PR for a specific use case. How can I do that?

**Comment by adamrbennett** [comment]
@ponsuyambu PR #37 will allow for approving pull requests. I am using it in my workflow to reject PRs that fail code analysis. You can checkout that branch, build it manually and install the hpi file into Jenkins.

**Comment by aaronwalker** [comment]
release in https://github.com/jenkinsci/pipeline-github-plugin/releases/tag/2.8-138.d766e30bb08b
