### ISSUE TITLE
GetProperty and SetProperty in WhiteList

### ISSUE THREAD

**Issue by Ramon-Balaguer** [jenkinsci/pipeline-github-plugin#8]
Can we mark this methods with "Whitelisted" to avoid problems with the sandbox?

https://github.com/jenkinsci/pipeline-github-plugin/blob/10aee3c11ddccf399856641914a1230cf90b90cf/src/main/java/org/jenkinsci/plugins/pipeline/github/PullRequestGroovyObject.java#L87

https://github.com/jenkinsci/pipeline-github-plugin/blob/10aee3c11ddccf399856641914a1230cf90b90cf/src/main/java/org/jenkinsci/plugins/pipeline/github/PullRequestGroovyObject.java#L263

When we want to acces:  pullRequest['created_by'] we have this error:

> org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String

**Comment by aaronjwhiteside** [comment]
I have an update in the works, basically removing the getProperty/setProperty methods and using real setters and getters. 

I can't simply whitelist these methods due to, https://jenkins.io/security/advisory/2017-07-10/#unsafe-methods-in-the-default-whitelist-in-script-security-plugin

**Comment by Ramon-Balaguer** [comment]
ok I watting this feature.

Tank you

**Comment by aaronjwhiteside** [comment]
Please see https://github.com/jenkinsci/pipeline-github-plugin/pull/9 I haven't done any extensive testing on the changes yet, but I'm putting them up for review if anyone has any feedback..

**Comment by tmcnag** [comment]
+1 on this.  I have a big array being built up by basically arbitrary strings and it will be nice to be able to loop over it in this way.

**Comment by aaronjwhiteside** [comment]
Version 2.0 has been released that includes these changes
