### ISSUE TITLE
Release 0.26.x

### ISSUE THREAD

**Issue by johncblandii** [jenkinsci/pipeline-github-plugin#83]
The environment variables are in a version > 0.25. Can we get the next release issued?

https://github.com/jenkinsci/pipeline-github-plugin#environment-variables.

**Comment by johncblandii** [comment]
![gif](https://media.giphy.com/media/vHwGAMZfWj3mU/giphy.gif)

**Comment by aaronjwhiteside** [comment]
It's coming, I'm just sorting out issues with my jenkins-ci account

**Comment by aaronjwhiteside** [comment]
2.7 is out! I thank everyone for their patience!
