### ISSUE TITLE
pullRequestReview Trigger Not Available

### ISSUE THREAD

**Issue by allout58** [jenkinsci/pipeline-github-plugin#96]
I am not able to use the `pullRequestReview` trigger with v2.7 installed.

With the trigger

```groovy
  triggers {
    pullRequestReview(reviewStates: ['approved'])
  }
```

I get the following errors trying to start the job
```
10:09:42  WorkflowScript: 10: Invalid trigger type "pullRequestReview". Valid trigger types: [upstream, cron, githubBranches, githubPullRequests, githubPush, issueCommentTrigger, pollSCM] @ line 10, column 5.
10:09:42         pullRequestReview(reviewStates: ['approved'])
```

I can see the issueCommentTrigger, but not the pullRequestReview trigger.

**Comment by alexbde** [comment]
Same here! Any update on this?

**Comment by pgAdmin** [comment]
@aaronwalker ^

**Comment by aaronwalker** [comment]
@allout58 @alexbde @pgAdmin I will push out a 2.8 release as soon as I am able to. Currently releases are disabled for all plugins due to a security event https://www.jenkins.io/blog/2021/09/04/wiki-attacked/

**Comment by pgAdmin** [comment]
Meanwhile I am using the master branch directly in my Jenkins server and it is working fine.

**Comment by aaronwalker** [comment]
Closing as releases now enabled again and release https://github.com/jenkinsci/pipeline-github-plugin/releases/tag/2.8-138.d766e30bb08b is now available
